长时间任务探查
ecodeclub/ecron pull request #24
Opened 2024-08-11 12:24 UTC by Jared-lu

2024-08-13 09:08 UTC, flycash reviewed
这个合并请求设计得不太对。

现在先集中解决 http 任务长时间运行探查状态的问题。那么 Scheduler 怎么探查呢？也是发 HTTP 请求给任务执行者，任务执行者上报进度。

所以关键是设计接口，我作为一个任务执行节点，我收到调度指令，我开始运行，而后我又收到进度探查的请求，我就上报。

先实现这种轮询的机制。

2024-08-13 09:08 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +		return cfg.TaskTimeout, nil
你在这里发起任务了之后，后续不就是要去探查任务进度了吗？或者说你集中探查的话，也是 Scheduler 探查。

2024-08-13 09:08 UTC, flycash commented on internal/reportor.go
> +type Reportor struct {
你这个看上去不是 reporter 啊，如果是 reporter 应该是在任务执行方，它们作为 SDK 引入的。这个你应该是接收者，应该让 Scheduler 去监控任务执行，探查任务进度

2024-08-13 09:10 UTC, flycash commented
![image](https://github.com/user-attachments/assets/05bebdc6-ed02-4b92-91c9-4d5ba77a8f4c)

2024-08-13 09:18 UTC, flycash commented
你需要定义清楚几个问题：
- local 需不需要探查？
- 当我调用一个 http 任务的时候，我怎么知道它已经彻底结束，还是正在执行，我后续需要继续发起 HTTP 请求来探查？
- 如果我要探查，我该怎么探查？HTTP 请求是怎样的，HTTP 响应该怎么规范？
- 我收到什么样的响应，认为这个长时间执行的任务已经结束？
- 如果我发现探查的时候收到的是超时响应，我应该怎么处理？
- 如果该任务最常的执行时间不能超过 30 分钟，而它已经超过三十分钟了，我是不是应该严格控制在恰好 30 分钟的时候就杀死这个任务（同样是发 HTTP 请求）？

2024-08-13 10:44 UTC, Jared-lu commented on internal/scheduler/preempt_scheduler.go
> +		return cfg.TaskTimeout, nil
意思是scheduler先要求executor执行一个任务，然后再告诉executor查一下当前任务的执行进度，executor发起探查后把结果返回给scheduler处理这样吗？是否探查任务进度以及探查进度的频率和超时处理都交给scheduler负责？
当前这一次的提交，我是在executor开始执行任务后就自动开启进度探查，然后executor把结果交给repotor去处理结果和记录执行进度情况。

2024-08-13 11:22 UTC, Jared-lu commented on internal/reportor.go
> +type Reportor struct {
这个是考虑后面允许用户主动上报进度时，有一个专门负责接收和处理上报结果的角色，由它负责将当前任务进度记录到storage。

2024-08-15 11:16 UTC, flycash commented on internal/reportor.go
> +type Reportor struct {
如果允许用户主动上报进度，你也是需要一个顶级接口。比如说我们讨论过你的上报可能是经过 HTTP，可能是经过 GRPC 也可能是走消息队列。这个 Reporter 同样是不合适的。

2024-08-15 11:17 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +		return cfg.TaskTimeout, nil
你可以让 executor 整个负责执行、探查的事情。这些事情的边界是有点模糊的，你让 executor 去做，让 scheduler 去做都可以，这不要紧，要紧的是你需要指定出来各种规范。

2024-08-15 11:17 UTC, flycash commented on internal/reportor.go
> +type Reportor struct {
类似与这种机制之类设计，是不可能用具体的实际的类型来表达的，必然是一个接口。

2024-08-25 09:03 UTC, flycash reviewed
这个探查机制已经符合我的预期了

2024-08-25 09:03 UTC, flycash commented on internal/executor/http.go
> +	default:
case StatusFailed 和 default 一样的，你可以把这个 StatusFailed 分支删除

2024-08-25 09:03 UTC, flycash commented on internal/executor/http.go
> +			request.Header.Set("execution_id", fmt.Sprintf("%v", eid))
和你的 Run 方法里面的代码重复了，试着抽取一下？

2024-08-25 09:03 UTC, flycash commented on internal/executor/http.go
> +			request.Header.Set("execution_id", fmt.Sprintf("%v", eid))
最好是 Run 和 explore 能复用整个发请求的代码，所不同的是 explore 这里要维护重试这种机制，以及监控用户取消或者超时

2024-08-25 09:03 UTC, flycash commented on internal/executor/http.go
> +			}
能不能通过抽取代码来复用这个这段，类似于：
```go
defer func() {
    if err != nil {
				if failCount >= h.maxFailCount {
					ch <- failResult
					return
				}
				failCount++
			}
}
```
这个代码很简单，偏偏一大堆的 if 分支，看起来挺累的。

2024-08-25 09:03 UTC, flycash commented on internal/executor/http.go
> +			request.Header.Set("execution_id", fmt.Sprintf("%v", eid))
或者：
```go
result, err := queryTaskStatus() 
// 把计数、发信号和对 error 的错误都合并在这里，上面 queryTaskStatus 就是老老实实返回 error 和查询结果
if err != xxx {
}
```

2024-08-25 09:03 UTC, flycash commented on internal/executor/http.go
> +	// 当业务方收到带有 Header cancel=true 的请求时，要停止执行任务
一样是可以服用的。可以尝试在 HttpCfg 上定义一个 NewRequest 的方法来放这些重复代码

2024-08-25 09:03 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +	p.explore(execCtx, exec, eid, t)
这个 explore 是不是只需要在状态是 running 的时候才需要执行？如果不是 running 的话，就说明已经结束。

2024-08-25 09:03 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +ForEnd:
不要用这个语法，它在后期非常难维护，而且可读性也很差。

2024-08-25 09:03 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +			default:
什么情况下会进来这里？是不是非法状态？如果是非法状态，我觉得可能需要打印一下日志，又或者和 Failed 的分支合并在一起

2024-08-25 09:03 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +		_ = p.executionDAO.UpdateProgress(ctx, eid, uint8(100))
正常来说，如果没有特别强力的理由，不要忽略错误

2024-08-29 09:24 UTC, flycash requested changes

2024-08-29 09:24 UTC, flycash commented on internal/executor/http.go
> +		default:
不能加这个 default 分支。因为你是要阻塞在前面两个分支里面，要么超时或者被取消，要么是到了探查的时候。

2024-08-29 09:24 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +	eid, err := p.executionDAO.InsertExecStatus(ctx, tid, status)
这里要用 upsert 语义，也就是你可以认为 tid 是唯一的

2024-08-29 09:24 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +	if status == task.ExecStatusSuccess {
这个分支就很奇怪。理论上来说，你这个方法不应该有这种特殊的处理，反正就是你 status 来了，我就更新一下，我不关心具体的 status

2024-08-29 09:24 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +				end = true
你将 executor.Status 直接转 task.Status，然后 makrStatus，代码就要清晰很多了。

2024-08-29 09:24 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +				err := p.executionDAO.UpdateProgress(ctx, eid, uint8(res.Progress))
整一块的代码没必要写那么复杂：
```go
// 转 task 的 status
status := from(exec.status)
// 直接无脑更新这两个字段
updateProgressStatus(ctx, eid, status, progress)
```

2024-08-29 09:24 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +	end := false
可以去掉这个标记位，end 赋值为 true 的地方直接返回

2024-08-29 09:24 UTC, flycash commented on internal/scheduler/preempt_scheduler.go
> +				_, _ = p.markStatus(t.ID, task.ExecStatusDeadlineExceeded)
error 都不能被忽略=。=

2024-08-29 09:24 UTC, flycash commented on internal/task/types.go
> +	ExecStatusRunning // 在语义上，与 ExecStatusStarted 没有区别
如果没有区别，要不把这两个合并为一个？

2024-08-29 09:24 UTC, flycash commented on internal/task/types.go
> +	ExecStatusRunning // 在语义上，与 ExecStatusStarted 没有区别
只用 RUNNING 或者 STARTED ？

2024-09-01 06:56 UTC, flycash approved these changes

2024-09-01 06:56 UTC, merged