增加Scheduler和HttpExecutor的初版实现
ecodeclub/ecron pull request #7
Opened 2023-02-06 10:43 UTC by hoysics

1. 增加Scheduler和Http executor实现;2. 此版使用轮询监听http执行进度

2023-02-08 13:45 UTC, flycash reviewed
你的 http 实现呢？

2023-02-08 13:45 UTC, flycash commented on internal/executor/types.go
> +	Execute(t *task.Task) <-chan scheduler.EventType
这里应该就是返回 Event，因为将来不仅仅是需要 type，可能还需要一些附加的数据

2023-02-16 15:02 UTC, hoysics commented on internal/executor/types.go
> +	Execute(t *task.Task) <-chan scheduler.EventType
....合并的时候搞漏了 晚点把http的补上 顺便把Event这里改下

2023-02-19 10:03 UTC, flycash requested changes

2023-02-19 10:03 UTC, flycash commented on internal/executor/http/executor.go
> +			time.Sleep(time.Second * time.Duration(info.Delay))
同样地，因为你一个任务就有一个 Goroutine 在这里轮询。那么如果我这个调度节点要调度十几万个任务，你这里就得开十几万个 goroutine。显然这是不太现实的，所以我才倾向于提供一个 /:task_name/status 这样的 API，只有一个goroutine 在这里，每次从延时队列里面拿一个 task，拿到了就查询一下状态。

当然这里也是可以优化的，比如说改为批量查询……不过核心还是在于并不能采用任务、goroutine 的 1:1 模型

2023-02-21 06:01 UTC, hoysics commented on internal/executor/http/executor.go
> +	Next:
我这里比较犹豫的是，如果已经要在执行节点上埋代理了，可不可以转由类似etcd这样的中间件存储当前节点的执行状态？首先这样相当于调度节点可能更方便的事件机制，只要执行节点的代理更新了状态，调度节点就会接收到事件然后进行后续操作。
当然肯定是要拆单独接口的，只是在接口内部和代理那里支持不同的实现。
（goto是个意外，也是我第一次用，想着场景比较简单就偷了个懒，下次改掉哈哈

2023-02-21 06:02 UTC, hoysics commented on internal/executor/http/executor.go
> +			time.Sleep(time.Second * time.Duration(info.Delay))
我也有过类似想法：有1个单独的监控Goroutine，当发起1个任务且这个任务执行时间较长的话，就向这个监控Goroutine发送当前任务的信息，由它来监控后续所有任务的执行状态。如果有任务执行完毕了，就通知调度Goroutine可以安排此任务的下一次执行。
不知道这样设计是否合理？

2023-02-24 09:11 UTC, flycash commented on internal/executor/http/executor.go
> +	Next:
其实你说到了一个很高级的东西，就是如何获得任务执行状态，应该提供一个高层次的抽象。那么我们可以设想：
- 类似于我这里提到的轮询
- 你提到的 etcd，或者我们可以统一称为借助第三方中间件更新状态，比如说 redis，zk 也是可以的
- 还有就是 kafka 等 MQ 机制

这个高层抽象其实我之前想过，但是因为实在有点复杂，所以我还没有考虑设计那么复杂的东西。如果你觉得 etcd 这种方案比较好，那么也不是不行。不过我希望你能有一个抽象，让这个代理在必要的时候可以切换到别的实现

2023-02-24 09:12 UTC, flycash commented on internal/executor/http/executor.go
> +	Next:
而且这个代理和任务配置（或者说调度核心）也算是一个强耦合的机制。比如说你代理采用了轮询，那么调度节点就应该要来轮询；又或者你代理这里用了 etcd，那么我调度节点就应该用 etcd。

2023-02-24 09:15 UTC, flycash commented on internal/executor/http/executor.go
> +			time.Sleep(time.Second * time.Duration(info.Delay))
难度在于你这个“发起一个任务且这个任务执行时间较长的话，就向监控 goroutine 发送当前任务的信息”。我觉得我们可以简化一个模型，就是我们发起 HTTP 调用，如果用户返回的是类似于"Accepted" 或者"处理中“的状态，那么我们就丢过去监控那里，如果我们直接就拿到结束（成功或者失败），那么就不用监控了。

当执行完毕之后，你应该只是发一个事件，有 Scheduler 决定要不要重试，以及如何重试。

2023-02-27 10:36 UTC, hoysics commented on internal/executor/http/executor.go
> +			time.Sleep(time.Second * time.Duration(info.Delay))
是的 我这里其实想表达也是这个意思：如果执行时间较长，就不是一直等待，而是返回状态，由单独的监控线程负责后续处理。这里就结合上面关于调度节点和监控节点的抽象一起进行实现。
如果是这样的话，我下一步开始设计调度节点和监控节点这一整块的抽象模型？

2023-02-27 12:38 UTC, flycash requested changes

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +	Payload string `json:"payload,omitempty"`
这里面我有一个困惑，就是什么场景下我们会考虑返回数据在这里？

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +func NewExecutor() *Executor {
最好这个 Client 让外面来传，因为你要考虑各种 https 之类的烦不胜烦

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +	Next:
可以的。暂时你要设计规范，这是首要条件。因为你要想，我们的目标是，用户可以用我们的代理，他也可以不用我们的代理。比如说有些人就是觉得你的代理神烦，他就是不乐意，那么他应该能够自己根据我们的 API 规范实现一个类似的代理。
虽然我觉得大多数人都没拿个闲情逸致。

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +		for k, v := range c.Header {
这里 mark 一个 TODO，因为后面我们要考虑鉴权的问题。

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +	}
这里抽象一个初始化 ApiConfig 的方法，里面完成默认值填充，就是你后面的 5s 啥的挪过来这里。这样后面我们有一个比较集中的地方看到各个字段的默认值。

然后对 ApiConfig 的校验也放在里面。这里保证 Execute 的逻辑清爽一点

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +	Next:
事件驱动的我们还要思考思考，我也暂时没有特别好的设计

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +		req, err := http.NewRequest(c.Method, c.URL, strings.NewReader(c.Payload))
NewRequest 的地方你直接指定 context.Context

2023-02-27 12:38 UTC, flycash commented on internal/executor/types.go
> +	EventTypeWaiting = "waiting"
改成 Running 比较好？Waiting 这个状态将来可能用得上，比如说我们丢过去执行节点，执行节点说我没有资源，你等一小会。

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +		switch info.Status {
每次看到这种呆代码我都无力吐槽 Go 的设计。后面我想办法搞一个 httpx 出来，神烦

2023-02-27 12:38 UTC, flycash commented on internal/executor/http/executor.go
> +			time.Sleep(time.Millisecond * time.Duration(info.Delay))
如果你这里用 Millisecond，那么我建议前面那里 5s 的也改为毫秒数。

2023-02-27 12:38 UTC, flycash commented on internal/scheduler/types_test.go
> +}
我记得 testing/httptest 是可以用来测试 http的，所以你可以切换过去。这种真的启动端口的，我想后面挪过去做 e2e 测试。或者你直接把这部分挪出去做 e2e 测试，然后再用 httptest 来做单元测试

2023-02-27 12:38 UTC, flycash commented on internal/task/types.go
> +		Need  bool
是不是不需要这个字段？如果 Count 是 0 或者负数，就不重试

2023-02-27 12:39 UTC, flycash commented on internal/executor/http/executor.go
> +			time.Sleep(time.Second * time.Duration(info.Delay))
okk

2023-02-27 14:59 UTC, hoysics commented on internal/executor/http/executor.go
> +	Payload string `json:"payload,omitempty"`
这里是我之前结合鉴权的一个粗糙的想法：

- 比如说如果这个执行节点是由用户自己实现的，轮询使用http请求查询执行进度的时候该如何告诉执行节点是要查询哪个任务的进度。
- 再比如，如果http请求涉及到token或者其他参数的更新，可以利用paylaod传递下次请求需要的信息。简而言之是给用户提供了一个自己控制轮询查询任务间隔和参数的机制。

但是如果现在我们会设计执行节点、代理层的抽象，那这块是可以抛弃的。因为有了代理以后，我上述的场景应该有更合适的解决方案

2023-02-27 15:07 UTC, hoysics commented on internal/executor/types.go
> +	EventTypeWaiting = "waiting"
那这里设计成这样几种状态如何

- 就绪（准备执行 ）Ready
- 执行中 Running
- 阻塞（等待资源）Waiting
- 失败（各种因素导致的任务中断执行或失败）Fail
- 成功 Success

2023-02-27 15:14 UTC, hoysics commented on internal/executor/http/executor.go
> +		for k, v := range c.Header {
鉴权这里的疑问是：如果执行节点的代理我们要进行抽象设计的话，鉴权是否应该也有对应的抽象层，并以拦截器的形式支持多种实现？

2023-02-27 15:14 UTC, hoysics commented on internal/task/types.go
> +		Need  bool
搞业务习惯留个明确字段清晰定义了，但整合一下确实清爽，下个版本改掉

2023-02-28 10:52 UTC, flycash commented on internal/executor/types.go
> +	EventTypeWaiting = "waiting"
Running 和 Waiting 之间可以相互转吗？比如说 Running 跑到一半，又需要 Waiting，然后又跳过来 Running

2023-02-28 10:53 UTC, flycash commented on internal/executor/http/executor.go
> +		for k, v := range c.Header {
是的，你会抢答了。
鉴权大体上有两大类，第一类就是通用的那种鉴权设计，比如说 Bearer token 这种；第二类就是用户自定义。那么还是那句话，如果我们打算提供代理，就应该允许用户自己开发代理。
因此我把代理定义为——一个为了便于用户使用的小玩具，不归属到核心里面。核心是你这里要提供的 API，即一个代理应该具备什么行为

2023-02-28 10:56 UTC, flycash commented on internal/executor/http/executor.go
> +	Payload string `json:"payload,omitempty"`
> 比如说如果这个执行节点是由用户自己实现的，轮询使用http请求查询执行进度的时候该如何告诉执行节点是要查询哪个任务的进度。

这里我一直设想的都是按名索引，比如说 /:task_name/status 这种接口，用户利用参数 task_name 就知道了。但是这里有一个缺陷，就是类似于一分钟执行一次这种，是否存在就是一个节点上运行了两次同一个 task? 

原则上我认为同样一个任务，在一个节点上应该最多存在一个运行实例。

我觉得你的顾虑有道理，暂时你先把这个注释掉，我们将来看看是不是真有这种奇诡的用法。我倒是觉得，在任务编排的时候，涉及到前置后置任务，这个字段说不定用得上。

2023-03-01 01:40 UTC, hoysics commented on internal/executor/types.go
> +	EventTypeWaiting = "waiting"
我认为不互转比较合适：一个任务可能是Ready转Running，也可能是Ready转Waiting转Running。但变成Running后，就应该默认这个任务需要的资源都已经筹齐了、应该执行到最后不能被打断。
如果支持这2种状态的互转，会增加任务调度的复杂度，比如Waiting状态中，是否认为这个节点能够执行其他任务、还要重新分配任务？这种灵活度开放出来的话，可能用户真的会有很多诡异操作。
而且除了前后置任务的场景中，暂时没考虑到其他对这种状态互转的需求。

2023-03-03 12:55 UTC, flycash commented
@hoysics 我先合并了一个雏形 mysql 实现进去，你记得合并一下。我后面要自己动手改一下那个 MySQL 的实现

2023-03-11 17:11 UTC, Stone-afk commented on internal/executor/http/executor.go
> +	Next:
mark

2023-03-14 02:20 UTC, flycash commented
我合并进去然后我自己改改

2023-03-14 02:20 UTC, merged